### ISSUE TITLE
How do I import it ?

### ISSUE THREAD

**Issue by peacefulotter** [rhayun/python-youtube-api#3]
So I can't figure it out : How can i import it ?

I tried everything, 
`import YoutubeAPI ; import youtube_api `
.... Nothing.

( also, sorry for my bad english im french ^^ )

**Comment by SpootDev** [comment]
It appears to be just one source file with one class in it.  If I use this this weekend I'll just import the "normal" way for classes in a source file instead of doing the setup.py.

**Comment by mgfcf** [comment]
So just copy the file to your project directory and import the file name `import youtubeapi` or if you just want to have the class `from youtubeapi import YoutubeAPI`.
